### ISSUE TITLE
Got Install issue

### ISSUE THREAD

**Issue by SaifulAzam** [SMATAR/laravel-settings#1]
When i run "php artisan vendor:publish" comment 

its give me error in my console.

> Can't locate path: </Users/username/Projects/test-app/vendor/smatar/laravel-settings/src/app/Providers/../../database/seeds>

**Comment by SMATAR** [comment]
Hi,
thank you for notifying me on this.

the fix pushed to master. please use

"smatar/laravel-settings": "dev-master"

in your composer, if you use v1.0 
till the new release of fixes released

thanks
